### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by carlgustavh** [MarcosNicolau/obsidian-for-academia#6]
I downloaded the font from here: https://www.fontsquirrel.com/fonts/latin-modern-roman
Yet the export is still the second in line standard serif font. Further proven by this codepen that I do not have the right font:
![image](https://github.com/MarcosNicolau/obsidian-for-academia/assets/95967108/865594c7-c227-4238-bdf2-d1ae1094edef)

**Comment by carlgustavh** [comment]
is it possible to import fonts in an obsidian css snippet?

**Comment by MarcosNicolau** [comment]
mmm... I'm not entirely sure. Have you tried looking it up on Google? You might find answers there.
