### ISSUE TITLE
Elaboration on "call the citations as @{{citekeys}}" in "Importing your annotations"

### ISSUE THREAD

**Issue by mafarkas** [MarcosNicolau/obsidian-for-academia#7]
Would it be possible to add some clarification as to why it matters to call citations as @{{citekeys}} in the output path? Mainly, what doing so enables. 

For example, I write personal notes but do not draft publications in Obsidian, so I do not cite from Obsidian and don't need that aspect of the integration. I am just getting started so perhaps I will find an issue later, but I seem to be doing fine so far with alternative file names, at least since I don't need that feature.

**Comment by MarcosNicolau** [comment]
It is useful because it allows you to cite a source and link it to the actual note you have imported.

If you don't need that, then you can call it as you like you won't have any issues.

**Comment by MarcosNicolau** [comment]
If that answers your question, you can close this issue. 

Thanks.
